In [2]:
import numpy as np
import numpy.ma as ma

In [3]:
a = np.array([np.nan]
            *20)

In [4]:
a

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan])

In [6]:
a = np.linspace(0,10,11)

In [7]:
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
b = ma.masked_array(a, list(map(lambda x: x%2, range(len(a)))))

In [10]:
b

masked_array(data=[0.0, --, 2.0, --, 4.0, --, 6.0, --, 8.0, --, 10.0],
             mask=[False,  True, False,  True, False,  True, False,  True,
                   False,  True, False],
       fill_value=1e+20)

In [17]:
c = np.zeros_like(a)
c[:] = np.nan
c[b.nonzero()] = b[b.nonzero()]

In [18]:
c

array([nan, nan,  2., nan,  4., nan,  6., nan,  8., nan, 10.])

(array([ 2,  4,  6,  8, 10]),)

In [19]:
list(map(lambda x: x%2, range(len(a))))

[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [20]:
c

array([nan, nan,  2., nan,  4., nan,  6., nan,  8., nan, 10.])

In [21]:
np.zeros_like(a)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
b.mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False])

In [43]:
available = np.array([0,5,10,12,14])
pixel_data = np.array([1,2,3,4,5])
masked_pixel_data = np.ma.masked_array(pixel_data, [0,0,0,1,0])

In [44]:
full_data = np.linspace(available[0], available[-1], available[-1]-available[0] + 1)
full_data[:] = np.nan
cur = np.ma.masked_array(available, masked_pixel_data.mask)
full_data[available[~cur.mask]] = masked_pixel_data[~cur.mask]

In [45]:
full_data

array([ 1., nan, nan, nan, nan,  2., nan, nan, nan, nan,  3., nan, nan,
       nan,  5.])

In [30]:
cur.mask

array([False,  True, False,  True, False])

In [31]:
available

[0, 5, 10, 12, 14]

In [33]:
available[np.array([True, False, False, False, True])]

TypeError: only integer scalar arrays can be converted to a scalar index